import type { AppProps } from "next/app";
import { Global, css } from "@emotion/react";
import React from "react";
import Head from "next/head";

const GlobalStyles = css`
  @import url("https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Open+Sans:wght@300;400;500;600;700;800&family=Merriweather:wght@300;400;700;900&display=swap");
  /* 
  font-family: 'Bebas Neue', cursive;
font-family: 'Open Sans', sans-serif;
font-family: 'Merriweather', serif;
*/
  :root {
    --bg: #191919;
    --white: #f6f6f6;
  }

  html,
  body {
    padding: 0;
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
      Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
    background: #191919;
    color: #fff;
  }
  * {
    box-sizing: border-box;
  }
`;

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Global styles={GlobalStyles} />
      <Component {...pageProps} />
    </>
  );
}
export default MyApp;
